---
version: 2
jobs:
  node-latest: &test_build
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum ".circleci/config.yml"}}-master
      - run: |
          if [[ ! -x "$(command -v shellcheck)" ]]; then
            apt-key update && apt-get update && apt-get install -y --force-yes shellcheck
          fi
      - run: cd test/fixtures/jest && yarn --frozen-lockfile
      - run: ./scripts/ci_run
      - save_cache: &save_cache
          key: v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - ~/cli/test/fixtures/jest/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
            - /usr/bin/shellcheck
  node-8:
    <<: *test_build
    docker:
      - image: node:8
  node-6:
    <<: *test_build
    docker:
      - image: node:6
  release:
    <<: *test_build
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn
      - run: npx semantic-release
      - save_cache: *save_cache

workflows:
  version: 2
  test:
    jobs:
      - node-latest
      - node-8
      - node-6
      - release:
          context: org-global
          filters:
            branches: {only: master}
          # requires:
          #   - node-latest
          #   - node-8
          #   - node-6
